#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /tmp/correction/5100344694032593162934247653951151444533_5/266/76640/0x0C-web_server/output/index.nginx-debian.html
sudo service nginx start
