#!/usr/bin/env bash
# set up web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw app list
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
sudo service nginx start
echo "Hello World!" > /var/www/html/index.html
