#!/usr/bin/env bash
# Installing a web server Nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
sudo service nginx reload
