#!/usr/bin/env bash
# A Bash script
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get -y install haproxy=2.0.\*
printf "\nfrontend haproxynode
        bind *:80
        mode http
        default_backend backendnodes
backend backendnodes
        balance roundrobin
        server 76640-web-01 100.26.209.169:80 check
        server 76640-web-02 54.160.85.51:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
